#!/bin/sh
set -e

# Dovecot container entrypoint
# Configures services based on env vars and starts Dovecot.

SQL_CONF=/etc/dovecot/dovecot-sql.conf.ext
LDAP_CONF=/etc/dovecot/dovecot-ldap.conf.ext
LISTENER_CONF=/etc/dovecot/conf.d/10-listeners.conf
AUTH_BACKEND_CONF=/etc/dovecot/conf.d/auth-backend.conf

mkdir -p /etc/dovecot/conf.d

DOVECOT_AUTH_DRIVER=${DOVECOT_AUTH_DRIVER:-mysql}

# ── Auth backend configuration ─────────────────────────────────────────────────

case "$DOVECOT_AUTH_DRIVER" in

  mysql|pgsql)
    if [ "$DOVECOT_AUTH_DRIVER" = "mysql" ]; then
        DB_HOST=${MYSQL_HOST:?ERROR: MYSQL_HOST is not set}
        DB_PORT=${MYSQL_PORT:-3306}
        DB_NAME=${MYSQL_DB:?ERROR: MYSQL_DB is not set}
        DB_USER=${MYSQL_USER:?ERROR: MYSQL_USER is not set}
        DB_PASS=${MYSQL_PASS:?ERROR: MYSQL_PASS is not set}
    else
        DB_HOST=${PGSQL_HOST:?ERROR: PGSQL_HOST is not set}
        DB_PORT=${PGSQL_PORT:-5432}
        DB_NAME=${PGSQL_DB:?ERROR: PGSQL_DB is not set}
        DB_USER=${PGSQL_USER:?ERROR: PGSQL_USER is not set}
        DB_PASS=${PGSQL_PASS:?ERROR: PGSQL_PASS is not set}
    fi

    # Write driver + connect line prepended to the static query file
    {
        printf 'driver = %s\n' "$DOVECOT_AUTH_DRIVER"
        printf 'connect = host=%s port=%s dbname=%s user=%s password=%s\n' \
            "$DB_HOST" "$DB_PORT" "$DB_NAME" "$DB_USER" "$DB_PASS"
        printf '\n'
        cat "$SQL_CONF"
    } > "${SQL_CONF}.tmp"
    mv "${SQL_CONF}.tmp" "$SQL_CONF"
    chmod 600 "$SQL_CONF"
    chown root:root "$SQL_CONF"

    cat > "$AUTH_BACKEND_CONF" << 'EOF'
passdb {
  driver = sql
  args   = /etc/dovecot/dovecot-sql.conf.ext
}

userdb {
  driver = sql
  args   = /etc/dovecot/dovecot-sql.conf.ext
}
EOF
    echo "dovecot: auth driver=$DOVECOT_AUTH_DRIVER ($DB_USER@$DB_HOST:$DB_PORT/$DB_NAME)"
    ;;

  ldap)
    LDAP_HOST=${LDAP_HOST:?ERROR: LDAP_HOST is not set}
    LDAP_PORT=${LDAP_PORT:-389}
    LDAP_BASE=${LDAP_BASE:?ERROR: LDAP_BASE is not set}
    LDAP_BIND_DN=${LDAP_BIND_DN:-}
    LDAP_BIND_PW=${LDAP_BIND_PW:-}
    LDAP_TLS=${LDAP_TLS:-no}
    # Default filter and attribute mapping match the standard vpopmail LDAP schema
    # (objectClass=qmailUser, mail=user@domain). Override if your schema differs.
    LDAP_USER_FILTER=${LDAP_USER_FILTER:-(&(objectClass=qmailUser)(mail=%u))}
    LDAP_PASS_ATTRS=${LDAP_PASS_ATTRS:-userPassword=password}
    LDAP_USER_ATTRS=${LDAP_USER_ATTRS:-homeDirectory=home,=uid=89,=gid=2109}

    cat > "$LDAP_CONF" << EOF
hosts = $LDAP_HOST:$LDAP_PORT
ldap_version = 3
tls = $LDAP_TLS
base = $LDAP_BASE
dn = $LDAP_BIND_DN
dnpass = $LDAP_BIND_PW
scope = subtree
auth_bind = no
default_pass_scheme = CRYPT
pass_filter = $LDAP_USER_FILTER
pass_attrs = $LDAP_PASS_ATTRS
user_filter = $LDAP_USER_FILTER
user_attrs = $LDAP_USER_ATTRS
iterate_filter = (objectClass=qmailUser)
iterate_attrs = mail=user
EOF
    chmod 600 "$LDAP_CONF"
    chown root:root "$LDAP_CONF"

    cat > "$AUTH_BACKEND_CONF" << 'EOF'
passdb {
  driver = ldap
  args   = /etc/dovecot/dovecot-ldap.conf.ext
}

userdb {
  driver = ldap
  args   = /etc/dovecot/dovecot-ldap.conf.ext
}
EOF
    echo "dovecot: auth driver=ldap ($LDAP_HOST:$LDAP_PORT base=$LDAP_BASE)"
    ;;

  *)
    echo "ERROR: unknown DOVECOT_AUTH_DRIVER=$DOVECOT_AUTH_DRIVER (use mysql, pgsql, or ldap)" >&2
    exit 1
    ;;
esac

# ── Generate listener configuration based on env vars ─────────────────────────
# Defaults: SSL ports enabled, plain ports disabled
DOVECOT_IMAP=${DOVECOT_IMAP:-false}
DOVECOT_IMAPS=${DOVECOT_IMAPS:-true}
DOVECOT_POP3=${DOVECOT_POP3:-false}
DOVECOT_POP3S=${DOVECOT_POP3S:-true}
DOVECOT_SIEVE=${DOVECOT_SIEVE:-true}
DOVECOT_LMTP=${DOVECOT_LMTP:-true}

mkdir -p /etc/dovecot/conf.d

cat > "$LISTENER_CONF" << 'HEADER'
# Dovecot listener configuration
# Generated by entrypoint.sh — do not edit manually.
# Configure via environment variables:
#   DOVECOT_IMAP=true/false   (port 143, default: false)
#   DOVECOT_IMAPS=true/false  (port 993, default: true)
#   DOVECOT_POP3=true/false   (port 110, default: false)
#   DOVECOT_POP3S=true/false  (port 995, default: true)
#   DOVECOT_SIEVE=true/false  (port 4190, default: true)
#   DOVECOT_LMTP=true/false   (port 24, default: true)

HEADER

# IMAP listeners
cat >> "$LISTENER_CONF" << EOF
service imap-login {
  inet_listener imap {
    port = $([ "$DOVECOT_IMAP" = "true" ] && echo "143" || echo "0")
  }
  inet_listener imaps {
    port = $([ "$DOVECOT_IMAPS" = "true" ] && echo "993" || echo "0")
    ssl  = yes
  }
}

EOF

# POP3 listeners
cat >> "$LISTENER_CONF" << EOF
service pop3-login {
  inet_listener pop3 {
    port = $([ "$DOVECOT_POP3" = "true" ] && echo "110" || echo "0")
  }
  inet_listener pop3s {
    port = $([ "$DOVECOT_POP3S" = "true" ] && echo "995" || echo "0")
    ssl  = yes
  }
}

EOF

# ManageSieve listener
cat >> "$LISTENER_CONF" << EOF
service managesieve-login {
  inet_listener sieve {
    port = $([ "$DOVECOT_SIEVE" = "true" ] && echo "4190" || echo "0")
  }
}

EOF

# LMTP listener (internal, for qmail delivery)
cat >> "$LISTENER_CONF" << EOF
service lmtp {
  inet_listener lmtp {
    address = 0.0.0.0
    port = $([ "$DOVECOT_LMTP" = "true" ] && echo "24" || echo "0")
  }
}
EOF

# Log enabled services
echo "dovecot: services enabled:"
[ "$DOVECOT_IMAP" = "true" ]  && echo "  - IMAP (143)"
[ "$DOVECOT_IMAPS" = "true" ] && echo "  - IMAPS (993)"
[ "$DOVECOT_POP3" = "true" ]  && echo "  - POP3 (110)"
[ "$DOVECOT_POP3S" = "true" ] && echo "  - POP3S (995)"
[ "$DOVECOT_SIEVE" = "true" ] && echo "  - ManageSieve (4190)"
[ "$DOVECOT_LMTP" = "true" ]  && echo "  - LMTP (24)"

# ── Wait for TLS certificates to be available ─────────────────────────────────
# The qmail container generates certs on first run; wait for them.
# maildata volume is mounted at /srv/qmail, with control files in qmail/control/
CERT_PATH=/srv/qmail/qmail/control/servercert.pem
WAIT_SECS=0
MAX_WAIT=120

while [ ! -f "$CERT_PATH" ]; do
    if [ "$WAIT_SECS" -ge "$MAX_WAIT" ]; then
        echo "ERROR: TLS cert not found at $CERT_PATH after ${MAX_WAIT}s" >&2
        exit 1
    fi
    echo "dovecot: waiting for TLS cert at $CERT_PATH..."
    sleep 5
    WAIT_SECS=$((WAIT_SECS + 5))
done

echo "dovecot: TLS cert found"

# ── Write rspamd credentials for IMAPSieve learn scripts ─────────────────────
# learn-spam.sh / learn-ham.sh source this file to POST to rspamd HTTP API.
RSPAMD_HOST=${RSPAMD_HOST:-rspamd}
RSPAMD_PORT=${RSPAMD_PORT:-11333}
RSPAMD_CONTROLLER_PORT=${RSPAMD_CONTROLLER_PORT:-11334}
RSPAMD_PASSWORD=${RSPAMD_PASSWORD:-}

mkdir -p /etc/dovecot/sieve
cat > /etc/dovecot/sieve/rspamd.env << EOF
RSPAMD_HOST=${RSPAMD_HOST}
RSPAMD_PORT=${RSPAMD_PORT}
RSPAMD_CONTROLLER_PORT=${RSPAMD_CONTROLLER_PORT}
RSPAMD_PASSWORD=${RSPAMD_PASSWORD}
EOF
chown vpopmail:vchkpw /etc/dovecot/sieve/rspamd.env
chmod 600 /etc/dovecot/sieve/rspamd.env

echo "dovecot: rspamd credentials written (${RSPAMD_HOST}:${RSPAMD_PORT}, controller:${RSPAMD_CONTROLLER_PORT})"

# ── Ensure mail directories exist with correct ownership ──────────────────────
chown -R vpopmail:vchkpw /srv/mail/vpopmail

# ── Start Dovecot in foreground ───────────────────────────────────────────────
echo "dovecot: starting..."
exec /usr/sbin/dovecot -F
