#!/bin/sh
set -e

# Dovecot container entrypoint
# Configures services based on env vars and starts Dovecot.

SQL_CONF=/etc/dovecot/dovecot-sql.conf.ext
LISTENER_CONF=/etc/dovecot/conf.d/10-listeners.conf

# ── Validate required environment variables ──────────────────────────────────
if [ -z "$MYSQL_HOST" ]; then
    echo "ERROR: MYSQL_HOST is not set" >&2
    exit 1
fi
if [ -z "$MYSQL_USER" ] || [ -z "$MYSQL_PASS" ] || [ -z "$MYSQL_DB" ]; then
    echo "ERROR: MYSQL_USER, MYSQL_PASS, or MYSQL_DB is missing" >&2
    exit 1
fi

MYSQL_PORT=${MYSQL_PORT:-3306}

# ── Write SQL connection string to dovecot-sql.conf.ext ───────────────────────
# Replace placeholder tokens with actual credentials
sed -i "s/MYSQL_HOST/${MYSQL_HOST}/g" "$SQL_CONF"
sed -i "s/MYSQL_PORT/${MYSQL_PORT}/g" "$SQL_CONF"
sed -i "s/MYSQL_DB/${MYSQL_DB}/g" "$SQL_CONF"
sed -i "s/MYSQL_USER/${MYSQL_USER}/g" "$SQL_CONF"
sed -i "s/MYSQL_PASS/${MYSQL_PASS}/g" "$SQL_CONF"

chmod 600 "$SQL_CONF"
chown root:root "$SQL_CONF"

echo "dovecot: SQL auth configured ($MYSQL_USER@$MYSQL_HOST:$MYSQL_PORT/$MYSQL_DB)"

# ── Generate listener configuration based on env vars ─────────────────────────
# Defaults: SSL ports enabled, plain ports disabled
DOVECOT_IMAP=${DOVECOT_IMAP:-false}
DOVECOT_IMAPS=${DOVECOT_IMAPS:-true}
DOVECOT_POP3=${DOVECOT_POP3:-false}
DOVECOT_POP3S=${DOVECOT_POP3S:-true}
DOVECOT_SIEVE=${DOVECOT_SIEVE:-true}
DOVECOT_LMTP=${DOVECOT_LMTP:-true}

mkdir -p /etc/dovecot/conf.d

cat > "$LISTENER_CONF" << 'HEADER'
# Dovecot listener configuration
# Generated by entrypoint.sh — do not edit manually.
# Configure via environment variables:
#   DOVECOT_IMAP=true/false   (port 143, default: false)
#   DOVECOT_IMAPS=true/false  (port 993, default: true)
#   DOVECOT_POP3=true/false   (port 110, default: false)
#   DOVECOT_POP3S=true/false  (port 995, default: true)
#   DOVECOT_SIEVE=true/false  (port 4190, default: true)
#   DOVECOT_LMTP=true/false   (port 24, default: true)

HEADER

# IMAP listeners
cat >> "$LISTENER_CONF" << EOF
service imap-login {
  inet_listener imap {
    port = $([ "$DOVECOT_IMAP" = "true" ] && echo "143" || echo "0")
  }
  inet_listener imaps {
    port = $([ "$DOVECOT_IMAPS" = "true" ] && echo "993" || echo "0")
    ssl  = yes
  }
}

EOF

# POP3 listeners
cat >> "$LISTENER_CONF" << EOF
service pop3-login {
  inet_listener pop3 {
    port = $([ "$DOVECOT_POP3" = "true" ] && echo "110" || echo "0")
  }
  inet_listener pop3s {
    port = $([ "$DOVECOT_POP3S" = "true" ] && echo "995" || echo "0")
    ssl  = yes
  }
}

EOF

# ManageSieve listener
cat >> "$LISTENER_CONF" << EOF
service managesieve-login {
  inet_listener sieve {
    port = $([ "$DOVECOT_SIEVE" = "true" ] && echo "4190" || echo "0")
  }
}

EOF

# LMTP listener (internal, for qmail delivery)
cat >> "$LISTENER_CONF" << EOF
service lmtp {
  inet_listener lmtp {
    address = 0.0.0.0
    port = $([ "$DOVECOT_LMTP" = "true" ] && echo "24" || echo "0")
  }
}
EOF

# Log enabled services
echo "dovecot: services enabled:"
[ "$DOVECOT_IMAP" = "true" ]  && echo "  - IMAP (143)"
[ "$DOVECOT_IMAPS" = "true" ] && echo "  - IMAPS (993)"
[ "$DOVECOT_POP3" = "true" ]  && echo "  - POP3 (110)"
[ "$DOVECOT_POP3S" = "true" ] && echo "  - POP3S (995)"
[ "$DOVECOT_SIEVE" = "true" ] && echo "  - ManageSieve (4190)"
[ "$DOVECOT_LMTP" = "true" ]  && echo "  - LMTP (24)"

# ── Wait for TLS certificates to be available ─────────────────────────────────
# The qmail container generates certs on first run; wait for them.
# maildata volume is mounted at /srv/qmail, with control files in qmail/control/
CERT_PATH=/srv/qmail/qmail/control/servercert.pem
WAIT_SECS=0
MAX_WAIT=120

while [ ! -f "$CERT_PATH" ]; do
    if [ "$WAIT_SECS" -ge "$MAX_WAIT" ]; then
        echo "ERROR: TLS cert not found at $CERT_PATH after ${MAX_WAIT}s" >&2
        exit 1
    fi
    echo "dovecot: waiting for TLS cert at $CERT_PATH..."
    sleep 5
    WAIT_SECS=$((WAIT_SECS + 5))
done

echo "dovecot: TLS cert found"

# ── Write rspamd credentials for IMAPSieve learn scripts ─────────────────────
# learn-spam.sh / learn-ham.sh source this file to POST to rspamd HTTP API.
RSPAMD_HOST=${RSPAMD_HOST:-rspamd}
RSPAMD_PORT=${RSPAMD_PORT:-11333}
RSPAMD_CONTROLLER_PORT=${RSPAMD_CONTROLLER_PORT:-11334}
RSPAMD_PASSWORD=${RSPAMD_PASSWORD:-}

mkdir -p /etc/dovecot/sieve
cat > /etc/dovecot/sieve/rspamd.env << EOF
RSPAMD_HOST=${RSPAMD_HOST}
RSPAMD_PORT=${RSPAMD_PORT}
RSPAMD_CONTROLLER_PORT=${RSPAMD_CONTROLLER_PORT}
RSPAMD_PASSWORD=${RSPAMD_PASSWORD}
EOF
chown vpopmail:vchkpw /etc/dovecot/sieve/rspamd.env
chmod 600 /etc/dovecot/sieve/rspamd.env

echo "dovecot: rspamd credentials written (${RSPAMD_HOST}:${RSPAMD_PORT}, controller:${RSPAMD_CONTROLLER_PORT})"

# ── Ensure mail directories exist with correct ownership ──────────────────────
chown -R vpopmail:vchkpw /srv/mail/vpopmail

# ── Start Dovecot in foreground ───────────────────────────────────────────────
echo "dovecot: starting..."
exec /usr/sbin/dovecot -F
