#!/bin/sh
# Called by IMAPSieve when a message is moved out of Junk/Spam.
# $1 — authenticated IMAP username (passed from Sieve via :args).
# Pipes message body to rspamd /learn_ham HTTP endpoint.
# Credentials sourced from rspamd.env generated by entrypoint.sh.

. /etc/dovecot/sieve/rspamd.env

USERNAME="${1:-}"

exec /usr/bin/curl --silent --show-error \
    -X POST \
    -H "Password: ${RSPAMD_PASSWORD}" \
    ${USERNAME:+-H "User: ${USERNAME}"} \
    "http://${RSPAMD_HOST}:${RSPAMD_PORT}/learn_ham" \
    --data-binary @-
