#!/bin/sh
# Called by IMAPSieve when a message is moved to Junk/Spam.
# $1 — authenticated IMAP username (passed from Sieve via :args).
# Pipes message body to rspamd /learn_spam HTTP endpoint.
# Credentials sourced from rspamd.env generated by entrypoint.sh.

. /etc/dovecot/sieve/rspamd.env

USERNAME="${1:-}"

RSPAMD_CONTROLLER_PORT=${RSPAMD_CONTROLLER_PORT:-11334}

exec /usr/bin/curl --silent --show-error \
    -X POST \
    -H "Password: ${RSPAMD_PASSWORD}" \
    ${USERNAME:+-H "User: ${USERNAME}"} \
    "http://${RSPAMD_HOST}:${RSPAMD_CONTROLLER_PORT}/learnspam" \
    --data-binary @-
