#!/bin/sh
QMAILDIR=$(getent passwd qmaild | cut -d: -f6)
QMAILDUID=$(id -u vpopmail)
NOFILESGID=$(id -g vpopmail)
MAXSMTPD=$(cat $QMAILDIR/control/concurrencyincoming)
SOFTLIMIT=$(cat $QMAILDIR/control/softlimit)
LOCAL=$(head -1 $QMAILDIR/control/me)
TCPRULES_DIR=$QMAILDIR/control
DUALSTACK=$(cat $QMAILDIR/control/dualstack 2>/dev/null || echo 0)
[ "$DUALSTACK" = "1" ] && BINDADDR="::" || BINDADDR="0"

# Auth required on port 587
export SMTPAUTH="!"
export SMTPD_GREETDELAY=3
export DROP_PRE_GREET=1
export CHKUSER_START=ALWAYS
export FORCEAUTHMAILFROM=1

exec chpst -m "$SOFTLIMIT" \
    /usr/local/bin/tcpserver -v -R -l "$LOCAL" \
    -x ${TCPRULES_DIR}/tcp.submission.cdb -c "$MAXSMTPD" \
    -u "$QMAILDUID" -g "$NOFILESGID" "$BINDADDR" 587 \
    $QMAILDIR/bin/qmail-smtpd \
    ~vpopmail/bin/vchkpw /bin/true 2>&1
